import { apiClient } from './client';
import type { Payment, TemplatesResponse } from '../types';

export const paymentApi = {
  createOrder: async (planType: string): Promise<{
    clientSecret: string; paymentIntentId: string; amount: number; currency: string;
  }> => {
    const response = await apiClient.post('/payment/create-order', { planType });
    return response.data;
  },

  verifyPayment: async (paymentIntentId: string): Promise<{ message: string; status: string }> => {
    const response = await apiClient.post('/payment/verify', { paymentIntentId });
    return response.data;
  },

  getHistory: async (): Promise<Payment[]> => {
    const response = await apiClient.get<Payment[]>('/payment/history');
    return response.data;
  },

  getOrderDetails: async (paymentIntentId: string): Promise<Payment> => {
    const response = await apiClient.get<Payment>(`/payment/order/${paymentIntentId}`)
    return response.data;
  },
};

export const templatesApi = {
  getTemplates: async (): Promise<TemplatesResponse> => {
    const response = await apiClient.get<TemplatesResponse>('/templates');
    return response.data;
  },
};

/**
 * Email API - sends resume as PDF file attachment.
 * pdfBlob is generated by the print iframe approach in the builder.
 */
export const emailApi = {
  sendResume: async (
    recipientEmail: string,
    subject: string,
    message: string,
    pdfBlob: Blob,
    filename: string
  ): Promise<{ success: boolean; message: string }> => {
    const formData = new FormData();
    formData.append('recipientEmail', recipientEmail);
    formData.append('subject', subject);
    formData.append('message', message);
    formData.append('pdfFile', new File([pdfBlob], filename, { type: 'application/pdf' }));

    const response = await apiClient.post('/email/send-resume', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
      timeout: 60000, // 60 seconds for large PDFs
    });
    return response.data;
  },
};
